name: falcon_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  animated_bottom_navigation_bar: ^1.3.3
  easy_date_timeline: ^1.1.3
  scroll_time_picker: ^1.0.2
  image_picker: ^1.1.2
  sqflite: ^2.0.3
  get_it: ^7.7.0
  intl:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

